-- Para crear la tabla en una base donde aún no existe.
USE alerta_temprana_v2;
CREATE TABLE contextos_permanencia (
	id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT, 
	matricula_id BIGINT UNSIGNED NOT NULL, 
	fecha_observacion DATE NOT NULL, 
	ventana_desde DATE NOT NULL, 
	fuente ENUM('APODERADO','ESTUDIANTE','DOCENTE','ORIENTADOR','DOCUMENTO_ESCOLAR') NOT NULL, 
	instrumento_version VARCHAR(80) NOT NULL, 
	origen ENUM('REAL','SIMULADO') NOT NULL, 
	registrado_por BIGINT UNSIGNED NOT NULL, 
	registrado_en DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, 
	actividades_propuestas SMALLINT UNSIGNED, 
	actividades_iniciadas SMALLINT UNSIGNED, 
	actividades_completadas SMALLINT UNSIGNED, 
	clases_observadas SMALLINT UNSIGNED, 
	clases_con_participacion SMALLINT UNSIGNED, 
	reuniones_convocadas SMALLINT UNSIGNED, 
	reuniones_atendidas SMALLINT UNSIGNED, 
	contactos_realizados SMALLINT UNSIGNED, 
	contactos_respondidos SMALLINT UNSIGNED, 
	acuerdos_evaluables SMALLINT UNSIGNED, 
	acuerdos_cumplidos SMALLINT UNSIGNED, 
	dificultad_lectura_observada BOOL, 
	dificultad_escritura_observada BOOL, 
	dificultad_calculo_observada BOOL, 
	necesita_apoyo_actividades BOOL, 
	dias_apoyo_estudio_semana TINYINT UNSIGNED, 
	espacio_estudio BOOL, 
	internet_estudio BOOL, 
	dispositivo_estudio BOOL, 
	adulto_referente_disponible BOOL, 
	repitencias_previas TINYINT UNSIGNED, 
	interrupciones_previas TINYINT UNSIGNED, 
	cambios_escuela_previos TINYINT UNSIGNED, 
	dificultades_integracion_reportadas BOOL, 
	acoso_reportado BOOL, 
	desmotivacion_reportada BOOL, 
	necesidad_apoyo_emocional_reportada BOOL, 
	PRIMARY KEY (id), 
	FOREIGN KEY(matricula_id) REFERENCES matriculas (id), 
	FOREIGN KEY(registrado_por) REFERENCES usuarios (id), 
	CONSTRAINT ck_contexto_ventana CHECK (ventana_desde <= fecha_observacion), 
	CONSTRAINT ck_contexto_fecha CHECK (fecha_observacion <= DATE(registrado_en)), 
	CONSTRAINT ck_cp_actividades_iniciadas CHECK (actividades_iniciadas <= actividades_propuestas), 
	CONSTRAINT ck_cp_actividades_completadas CHECK (actividades_completadas <= actividades_iniciadas), 
	CONSTRAINT ck_cp_clases_con_participacion CHECK (clases_con_participacion <= clases_observadas), 
	CONSTRAINT ck_cp_reuniones_atendidas CHECK (reuniones_atendidas <= reuniones_convocadas), 
	CONSTRAINT ck_cp_contactos_respondidos CHECK (contactos_respondidos <= contactos_realizados), 
	CONSTRAINT ck_cp_acuerdos_cumplidos CHECK (acuerdos_cumplidos <= acuerdos_evaluables), 
	CONSTRAINT ck_contexto_apoyo CHECK (dias_apoyo_estudio_semana BETWEEN 0 AND 7), 
	CONSTRAINT ck_cp_bool_0 CHECK (dificultad_lectura_observada IN (0,1)), 
	CONSTRAINT ck_cp_bool_1 CHECK (dificultad_escritura_observada IN (0,1)), 
	CONSTRAINT ck_cp_bool_2 CHECK (dificultad_calculo_observada IN (0,1)), 
	CONSTRAINT ck_cp_bool_3 CHECK (necesita_apoyo_actividades IN (0,1)), 
	CONSTRAINT ck_cp_bool_4 CHECK (espacio_estudio IN (0,1)), 
	CONSTRAINT ck_cp_bool_5 CHECK (internet_estudio IN (0,1)), 
	CONSTRAINT ck_cp_bool_6 CHECK (dispositivo_estudio IN (0,1)), 
	CONSTRAINT ck_cp_bool_7 CHECK (adulto_referente_disponible IN (0,1)), 
	CONSTRAINT ck_cp_bool_8 CHECK (dificultades_integracion_reportadas IN (0,1)), 
	CONSTRAINT ck_cp_bool_9 CHECK (acoso_reportado IN (0,1)), 
	CONSTRAINT ck_cp_bool_10 CHECK (desmotivacion_reportada IN (0,1)), 
	CONSTRAINT ck_cp_bool_11 CHECK (necesidad_apoyo_emocional_reportada IN (0,1))
)ENGINE=InnoDB CHARSET=utf8mb4 COLLATE utf8mb4_0900_ai_ci;
CREATE INDEX ix_contexto_corte ON contextos_permanencia (matricula_id, fecha_observacion, registrado_en);
