-- Solo para la ficha anterior VACIA; preferir el migrador Python que verifica esa condición.
USE alerta_temprana_v2;
ALTER TABLE contextos_permanencia
  DROP CHECK `ck_contexto_apoyo`,
  DROP CHECK `ck_contexto_cuidado`,
  DROP CHECK `ck_contexto_fecha`,
  DROP CHECK `ck_contexto_trabajo`,
  DROP CHECK `ck_contexto_traslado`,
  DROP CHECK `ck_contexto_ventana`,
  DROP CHECK `ck_cp_bool_0`,
  DROP CHECK `ck_cp_bool_1`,
  DROP CHECK `ck_cp_bool_10`,
  DROP CHECK `ck_cp_bool_11`,
  DROP CHECK `ck_cp_bool_2`,
  DROP CHECK `ck_cp_bool_3`,
  DROP CHECK `ck_cp_bool_4`,
  DROP CHECK `ck_cp_bool_5`,
  DROP CHECK `ck_cp_bool_6`,
  DROP CHECK `ck_cp_bool_7`,
  DROP CHECK `ck_cp_bool_8`,
  DROP CHECK `ck_cp_bool_9`,
  DROP COLUMN `alimentacion_insuficiente`,
  DROP COLUMN `cambios_domicilio_12_meses`,
  DROP COLUMN `dificultad_gastos_escolares`,
  DROP COLUMN `horas_cuidado_semana`,
  DROP COLUMN `horas_trabajo_semana`,
  DROP COLUMN `materiales_disponibles`,
  DROP COLUMN `minutos_traslado`,
  DROP COLUMN `transporte_disponible`,
  ADD COLUMN actividades_completadas SMALLINT UNSIGNED,
  ADD COLUMN actividades_iniciadas SMALLINT UNSIGNED,
  ADD COLUMN actividades_propuestas SMALLINT UNSIGNED,
  ADD COLUMN acuerdos_cumplidos SMALLINT UNSIGNED,
  ADD COLUMN acuerdos_evaluables SMALLINT UNSIGNED,
  ADD COLUMN clases_con_participacion SMALLINT UNSIGNED,
  ADD COLUMN clases_observadas SMALLINT UNSIGNED,
  ADD COLUMN contactos_realizados SMALLINT UNSIGNED,
  ADD COLUMN contactos_respondidos SMALLINT UNSIGNED,
  ADD COLUMN dificultad_calculo_observada BOOL,
  ADD COLUMN dificultad_escritura_observada BOOL,
  ADD COLUMN dificultad_lectura_observada BOOL,
  ADD COLUMN necesita_apoyo_actividades BOOL,
  ADD COLUMN reuniones_atendidas SMALLINT UNSIGNED,
  ADD COLUMN reuniones_convocadas SMALLINT UNSIGNED,
  ADD CONSTRAINT `ck_cp_bool_2` CHECK (dificultad_calculo_observada IN (0,1)),
  ADD CONSTRAINT `ck_cp_bool_10` CHECK (desmotivacion_reportada IN (0,1)),
  ADD CONSTRAINT `ck_cp_actividades_completadas` CHECK (actividades_completadas <= actividades_iniciadas),
  ADD CONSTRAINT `ck_cp_bool_3` CHECK (necesita_apoyo_actividades IN (0,1)),
  ADD CONSTRAINT `ck_cp_bool_11` CHECK (necesidad_apoyo_emocional_reportada IN (0,1)),
  ADD CONSTRAINT `ck_cp_clases_con_participacion` CHECK (clases_con_participacion <= clases_observadas),
  ADD CONSTRAINT `ck_cp_bool_4` CHECK (espacio_estudio IN (0,1)),
  ADD CONSTRAINT `ck_cp_reuniones_atendidas` CHECK (reuniones_atendidas <= reuniones_convocadas),
  ADD CONSTRAINT `ck_cp_bool_5` CHECK (internet_estudio IN (0,1)),
  ADD CONSTRAINT `ck_cp_contactos_respondidos` CHECK (contactos_respondidos <= contactos_realizados),
  ADD CONSTRAINT `ck_cp_bool_6` CHECK (dispositivo_estudio IN (0,1)),
  ADD CONSTRAINT `ck_cp_acuerdos_cumplidos` CHECK (acuerdos_cumplidos <= acuerdos_evaluables),
  ADD CONSTRAINT `ck_cp_bool_7` CHECK (adulto_referente_disponible IN (0,1)),
  ADD CONSTRAINT `ck_contexto_apoyo` CHECK (dias_apoyo_estudio_semana BETWEEN 0 AND 7),
  ADD CONSTRAINT `ck_contexto_ventana` CHECK (ventana_desde <= fecha_observacion),
  ADD CONSTRAINT `ck_cp_bool_0` CHECK (dificultad_lectura_observada IN (0,1)),
  ADD CONSTRAINT `ck_cp_bool_8` CHECK (dificultades_integracion_reportadas IN (0,1)),
  ADD CONSTRAINT `ck_contexto_fecha` CHECK (fecha_observacion <= DATE(registrado_en)),
  ADD CONSTRAINT `ck_cp_bool_9` CHECK (acoso_reportado IN (0,1)),
  ADD CONSTRAINT `ck_cp_bool_1` CHECK (dificultad_escritura_observada IN (0,1)),
  ADD CONSTRAINT `ck_cp_actividades_iniciadas` CHECK (actividades_iniciadas <= actividades_propuestas);